### PR TITLE
add timeframe for automatic votes

### PR DESCRIPTION
**Pull request by Coolisbetter**
Logic tested on jsfiddle, didn't test within squadJS

### CODE REVIEW

**Comment by leohero6** [comment]
When I try to start a vote, for example, only with invasion, only the title VOTEMAP appears and no option to vote. But when I see the log, the options appear normally.

**Comment by leohero6** [comment]
How do I report an issue here in this repo? When I try to open an issue it opens on the plugin page comes from maskedmonkyman. Im newbie here in github.

**Comment by Coolisbetter** [comment]
> How do I report an issue here in this repo? When I try to open an issue it opens on the plugin page comes from maskedmonkyman. Im newbie here in github.

He doesn't have issues enabled on this repo. If you have an issue, come to the discord: https://discord.gg/kvG2KB2NNK

**Comment by fantinodavide** [comment]
Timeframes implemented for every option.

P.S. Issues enabled

**Pull request closed without merging**
